; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino

[env:nano_test_LED]
platform = atmelavr
board = nanoatmega328new
framework = arduino
; Only run select files
build_src_filter =     
;   removes all files 
    -<*>
;   adds back some of the files 
    +<main.cpp>
    +<LED.h>
    +<LED.cpp>

[env:esp]
platform = espressif32
board =  fm-devkit
framework = arduino