; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps = https://github.com/LUMA-Balloon/Two-Month-Libraries.git

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
lib_deps = adafruit/Adafruit BME280 Library@^2.3.0

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps = adafruit/Adafruit BME280 Library@^2.3.0

[env:nano_test_LED]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_src_filter = 
	-<*>
	+<main.cpp>
	+<LED.h>
	+<LED.cpp>
lib_deps = adafruit/Adafruit BME280 Library@^2.3.0

[env:esp]
platform = espressif32
board = fm-devkit
framework = arduino
lib_deps = adafruit/Adafruit BME280 Library@^2.3.0
